export const errorTypes = {
    APP_ERROR_RESET: 'APP_ERROR_RESET',
    API_RETURN_FAILURE: 'API_RETURN_FAILURE',
    API_RETURN_SUCCESS: 'API_RETURN_SUCCESS',
    APP_NO_CONNECTION: 'APP_NO_CONNECTION',
    APP_PAGE_NOT_FOUND: 'APP_PAGE_NOT_FOUND'
};
