export const drivenTypes = {
    APP_LOADING_ACTIVE: 'APP_LOADING_ACTIVE',
    APP_PROCESSING_ACTIVE: 'APP_PROCESSING_ACTIVE',
    APP_ANIMATE_INACTIVE: 'APP_ANIMATE_INACTIVE',
    APP_NO_LOADING: 'APP_NO_LOADING'
};
