export const wpTypes = {
    WP_JOB_RESET: 'WP_JOB_RESET',
    WP_LOADING_JOB_DETAIL_ACTIVE: 'WP_LOADING_JOB_DETAIL_ACTIVE',
    WP_CREATE_JOB_SUCCESS: 'WP_CREATE_JOB_SUCCESS',

    WP_READ_JOB_SUCCESS: 'WP_READ_JOB_SUCCESS',
    WP_READ_JOB_DETAIL_SUCCESS: 'WP_READ_JOB_DETAIL_SUCCESS',
    WP_READ_JOB_EDITER_SUCCESS: 'WP_READ_JOB_EDITER_SUCCESS',
    WP_JOB_EDITER_RESET: 'WP_JOB_EDITER_RESET',
    // sub-job-info
    WP_READ_JOB_OWNER_INFO_SUCCESS: 'WP_READ_JOB_OWNER_INFO_SUCCESS',
    WP_READ_JOB_OWNER_ADDR_SUCCESS: 'WP_READ_JOB_OWNER_ADDR_SUCCESS',
    WP_READ_JOB_ADDR_SUCCESS: 'WP_READ_JOB_ADDR_SUCCESS',
    WP_READ_JOB_INDUSTRY_SUCCESS: 'WP_READ_JOB_INDUSTRY_SUCCESS',
    WP_READ_JOB_LEVEL_SUCCESS: 'WP_READ_JOB_LEVEL_SUCCESS',
    WP_READ_JOB_SALARY_SUCCESS: 'WP_READ_JOB_SALARY_SUCCESS',

    WP_UPDATE_JOB_SUCCESS: 'WP_UPDATE_JOB_SUCCESS',
    WP_DELETE_JOB_SUCCESS: 'WP_DELETE_JOB_SUCCESS',

    WP_LIKE_JOB_REQUEST: 'WP_LIKE_JOB_REQUEST',
    WP_LIKE_JOB_SUCCESS: 'WP_LIKE_JOB_SUCCESS',

    WP_SAVE_JOB_REQUEST: 'WP_SAVE_JOB_REQUEST',
    WP_SAVE_JOB_SUCCESS: 'WP_SAVE_JOB_SUCCESS',

    WP_SHARE_JOB_REQUEST: 'WP_SHARE_JOB_REQUEST',
    WP_SHARE_JOB_SUCCESS: 'WP_SHARE_JOB_SUCCESS',
    WP_RESET_SHARE_JOB: 'WP_RESET_SHARE_JOB',

    WP_SWITCH_TO_MODE_BROKER_SUCCESS: 'WP_SWITCH_TO_MODE_BROKER_SUCCESS',
};                   